// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI56tZpBAFRPj_LIYJa6DvPAk-obAsi7o',
    appId: '1:62416261079:web:bc0dfd28bc9eb779cfc592',
    messagingSenderId: '62416261079',
    projectId: 'todo-fea95',
    authDomain: 'todo-fea95.firebaseapp.com',
    storageBucket: 'todo-fea95.appspot.com',
    measurementId: 'G-SK2FBMKP4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQhlOfNDr_gkiKBSnTYPeJzR0Hh0fkoyo',
    appId: '1:62416261079:android:a7c7c2a17acb91d8cfc592',
    messagingSenderId: '62416261079',
    projectId: 'todo-fea95',
    storageBucket: 'todo-fea95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPsgZuh5lzGtRCGhU7AQyVX7FwT0jgeBk',
    appId: '1:62416261079:ios:d7da46ba0a5e5a39cfc592',
    messagingSenderId: '62416261079',
    projectId: 'todo-fea95',
    storageBucket: 'todo-fea95.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPsgZuh5lzGtRCGhU7AQyVX7FwT0jgeBk',
    appId: '1:62416261079:ios:f1aa12585370a846cfc592',
    messagingSenderId: '62416261079',
    projectId: 'todo-fea95',
    storageBucket: 'todo-fea95.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
